apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-agent-config
data:
  datadog.yaml: |
    api_key: ${DD_API_KEY}
    site: datadoghq.com
    logs_enabled: true
    apm_config:
      enabled: true
    process_config:
      enabled: true
    logs_config:
      container_collect_all: true
    listeners:
      - name: kubelet
    config_providers:
      - name: kubelet
        polling: true
    docker_labels_as_tags:
      app: app_name
    kubernetes_pod_labels_as_tags:
      app: app_name
      environment: env
    tags:
      - env:production
      - service:scheduler
      - team:backend
    integrations:
      mongodb:
        instances:
          - host: mongodb://localhost:27017
            database: scheduler
      redis:
        instances:
          - host: localhost
            port: 6379
      nginx:
        instances:
          - nginx_status_url: http://localhost:8080/nginx_status 