apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero-server
rules:
- apiGroups:
  - velero.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-server
subjects:
- kind: ServiceAccount
  name: velero-server
  namespace: velero
roleRef:
  kind: ClusterRole
  name: velero-server
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-server
  namespace: velero 