apiVersion: v1
kind: Secret
metadata:
  name: snap-codex-scheduler-secrets
  namespace: snap-codex
  annotations:
    kubernetes.io/service-account.name: snap-codex-scheduler
type: Opaque
stringData:
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_REGION: ${AWS_REGION}
  AWS_S3_BUCKET: ${AWS_S3_BUCKET}
  JWT_SECRET: ${JWT_SECRET} 