name: 기능 개발
description: 새로운 기능 개발을 위한 이슈 템플릿
title: "[Feature]: "
labels: ["feature"]
body:
  - type: dropdown
    id: category
    attributes:
      label: 개발 주제
      options:
        - UI/UX
        - 인증/권한
        - 캘린더 연동
        - 데이터 모델
        - 상태 관리
        - API 통합
        - 테스트
    validations:
      required: true
  
  - type: input
    id: completion-percentage
    attributes:
      label: 진행률
      description: "현재 진행률을 입력해주세요 (0-100)"
      placeholder: "예: 75"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      description: 구현할 기능에 대해 설명해주세요
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 완료 조건
      description: 이 기능이 완료되었다고 판단할 수 있는 조건들을 나열해주세요
      value: |
        - [ ] 조건 1
        - [ ] 조건 2
        - [ ] 조건 3
    validations:
      required: true

  - type: textarea
    id: technical-details
    attributes:
      label: 기술적 세부사항
      description: 구현에 필요한 기술적 세부사항을 작성해주세요
    validations:
      required: false 