name: PR Agent
on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    name: Run PR Agent on PR
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: PR Agent action
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          review_comment_path: '.github/pr_agent_templates/review.md'
          summary_comment_path: '.github/pr_agent_templates/summary.md' 